### ISSUE TITLE
crash on gpu mode, but work by cpu

### ISSUE THREAD

**Issue by vzvzx** [DaFuCoding/MTCNN_Caffe#1]
change link below, if someone else has the same problam

MTCNN::MTCNN(const std::string &proto_model_dir){
//#ifdef CPU_ONLY
  Caffe::set_mode(Caffe::CPU);
//#else
//  Caffe::set_mode(Caffe::GPU);
//#endif

**Comment by zhonhel** [comment]
I got error on GPU too，how to solve it？
