### ISSUE TITLE
can mtcnn support grayscale image for speed boost?

### ISSUE THREAD

**Issue by yxchng** [DaFuCoding/MTCNN_Caffe#13]

**Comment by DaFuCoding** [comment]
No. Because the channel of input must be three.
But this isn't speed bottleneck.

**Comment by yxchng** [comment]
Then what is the bottleneck?

**Comment by DaFuCoding** [comment]
I think
1. CPU and GPU exchange information frequently.
2. Pnet is main time consuming in whole algorithm.
