### ISSUE TITLE
Questions about part of the code

### ISSUE THREAD

**Issue by yxchng** [DaFuCoding/MTCNN_Caffe#14]
int count = confidence->count()/2;
const float* confidence_data = confidence->cpu_data();
confidence_data += count;
const float* reg_data = reg->cpu_data();

Can I know why here confidence_data += count, but reg_data doesn't += count?

**Comment by DaFuCoding** [comment]
The "confidence" is result of softmax. First half is non-face score, and back half is face score. Their sum is one. You just use one to judge proposals.
The reg_data result is offset of regression.
