### ISSUE TITLE
conv_layer.cu

### ISSUE THREAD

**Issue by yja1** [DaFuCoding/MTCNN_Caffe#15]
Forward_gpu() has:
//        const Dtype* tempTop = top[0]->gpu_data();
//        for(int i=0;i<10;i++){
//          std::cout<<*(tempTop+i)<<std::endl;
//        }

为啥会出现这几行代码？直接打印gpu上的数据没有报错？

**Comment by DaFuCoding** [comment]
This is Caffe's code source.
