### ISSUE TITLE
Train own models

### ISSUE THREAD

**Issue by joshua19881228** [DaFuCoding/MTCNN_Caffe#16]
Thanks for the great work. 

Can this repo be used for training my own models?

**Comment by DaFuCoding** [comment]
@joshua19881228 Sorry, I didn't offer the MTCNN training code. I try some deep learning framework, such as Tensorflow , caffe, mxnet, but these training code didn't achieve author's performance in FDDB.
I recommend https://github.com/Seanlinx/mtcnn by mxnet. 
I will keep trying training this algorithm.

**Comment by joshua19881228** [comment]
@DaFuCoding Sure and thanks for your recommendation.
