### ISSUE TITLE
batch测试

### ISSUE THREAD

**Issue by yja1** [DaFuCoding/MTCNN_Caffe#17]
请问我想改成按照一个batch来测试，要怎么改呢？麻烦么？

**Comment by DaFuCoding** [comment]
@yja1 你说的batch是pnet还是rnet,onet? 
如果是pnet输入的话， 如果是Test阶段默认batch=1
如果是rnet或者是onet, ClassifyFace 代替 ClassifyFace_MulImage， 但是如果使用ClassifyFace最好使用CPU， 因为使用GPU有些还没有解决的问题。

**Comment by yja1** [comment]
首先感谢您的回复。
我是想要做多路视频的检测（GPU），所以要求速度。想通过提高batch来提速（虽然我测的三个网络的时间并不是耗时的关键，但是增大batch总不会慢）。周五我已经改差不多了。

**Comment by DaFuCoding** [comment]
OK, 如代码有什么问题随时提问， 祝你成功～

**Comment by sunjunlishi** [comment]
ClassifyFace_MulImage 感觉 GPU 执行 错误，难道 必须用你的 layer ？
ClassifyFace GPU 就没有问题。
@DaFuCoding 模型比其他模型都要快
