### ISSUE TITLE
图像转置

### ISSUE THREAD

**Issue by liujs19** [DaFuCoding/MTCNN_Caffe#21]
您好，我想请问：Detect里为什么要对图像转置（ sample_single = sample_single.t();）？

**Comment by sunjunlishi** [comment]
same asking.......

**Comment by sunjunlishi** [comment]
因为原作者是利用matlab进行训练的，在matlab中加载图片与opencv加载图片方式不同，相差一个转置。并且caffe中默认卷积操作是按照行优先进行的，为了不修改caffe源码，所以进行了转置操作。
--coming from DaFuCoding.
