### ISSUE TITLE
速度 GTX980 耗时400ms 

### ISSUE THREAD

**Issue by twinsyssy1018** [DaFuCoding/MTCNN_Caffe#3]
您好，我用这个代码测试了下test1,test2.jpg 速度并不快，约400-500ms  每张  。就算是将minsize改到30，40 也没有多少变化。 请问你写的20ms是多大尺寸的图片？

**Comment by jay2002** [comment]
用1080的卡测，640x480的图，速度大概80ms左右，同好奇……

**Comment by kuangliu** [comment]
NVIDIA K40m 50ms.

**Comment by twinsyssy1018** [comment]
我找到我的问题了，机器内存不足，同时跑好几个gpu程序时才这么慢， 单独跑这个，也得80ms左右

**Comment by flexibility2** [comment]
@twinsyssy1018 ,同学你好，请问你是怎么解决这个问题的啊？我用单GPU，GTX1080 Ti测试，速度是500ms……
