### ISSUE TITLE
segement err

### ISSUE THREAD

**Issue by yja1** [DaFuCoding/MTCNN_Caffe#5]
if #define CPU_ONLY the project work ok
if use gpu the work error at function MTCNN::Detect(const cv::Mat& image,std::vector<FaceInfo>& faceInfo,int minSize,double* threshold,double factor)
line PNet_->Forward();
thx

**Comment by zhonhel** [comment]
How did you solve this problem？

**Comment by yja1** [comment]
in conv layer .cu file delete 3 lines
        for(int i=0;i<10;i++){
          std::cout<<*(tempTop+i)<<std::endl;
        }
maybe author output this for debug. but this is on GPU.

**Comment by zhonhel** [comment]
@yja1 
Thank you very much!
This indeed solved this problem.
